# Generated by Django 5.2.2 on 2025-06-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlantillaExcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "enlace_descarga",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("imagen_url", models.URLField(blank=True, max_length=500, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plantilla de Excel",
                "verbose_name_plural": "Plantillas de Excel",
            },
        ),
    ]
